name: "Workflow Cleanup"
on:
  schedule:
    - cron: '0 0 */7 * *'
# Run monthly, at 00:00 on the 1st day of month.
# https://github.com/marketplace/actions/delete-workflow-runs
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
          delete_workflow_by_state_pattern: "All"
          delete_run_by_conclusion_pattern: "All"
