name: Docker Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build --tag minimal-api --file ./MinimalApi/Dockerfile .

    - name: Run Docker image
      run: docker run --name minimal-api-container -p 8081:80 -p 8082:443 -d minimal-api
    
    - name: Check Health Probe
      id: probe_info
      run: |
        content=`curl http://localhost:8081/health`
        echo "::set-output name=packageJson::$content"
        
    - run: |
        echo "${{fromJson(steps.probe_info.outputs.packageJson).HealthStatus}}"
