name: Docker Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'

    - name: Install newman
      run: |
        npm install -g newman

    - name: Build Docker image
      run: docker build --tag minimal-api --file ./MinimalApi/Dockerfile .

    - name: Run Docker image
      run: docker run --name minimal-api-container -p 8081:80 -p 8082:443 -d minimal-api

    - name: Test
      run: |
        newman run ./Tests/health_probe_tests.json -r cli
