name: Docker Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build --tag minimal-api --file ./MinimalApi/Dockerfile .

    - name: Run Docker image
      run: docker run --name minimal-api-container -p 8081:80 -p 8082:443 -d minimal-api
    
    - name: Check Health Probe
      uses: lakuapik/gh-actions-http-status@v1
      with:
        # List website urls in JSON (eg: ["http://github.com", "https://education.github.com"])
        sites: "http://localhost:8081/heaasdflth"
        # List expected HTTP status codes in JSON (eg: [301, 200])
        expected: 200
      
    #- name: Check Health Probe
    #  id: check_probe
    #  run: curl -o /dev/null -s -w "%{http_code}\n"  http://localhost:8081/health >> $GITHUB_OUTPUT
      
    #- name: Assert Health
    #  uses: nick-fields/assert-action@v1.2.0
    #  with:
    #    # Expected value
    #    expected: 200
    #    # Actual value
    #    actual: ${{ steps.check_probe.outputs.value }}
