name: "Build (CCSR & Sticky)"

on:
  workflow_dispatch:
    
permissions: write-all    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --filter "Category!=IntegrationTest" --no-build --verbosity normal
      
    - name: Test with coverage
      run: dotnet test --filter "Category!=IntegrationTest" --collect:"XPlat Code Coverage" --settings Tests/coverlet.runsettings
      
    - name: Move coverage report
      run: mv ./Tests/TestResults/*/coverage.cobertura.xml ./Tests/TestResults/coverage.cobertura.xml
      
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.0.2
      with:
        filename: Tests/TestResults/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'
        thresholds: '60 80'
        indicators: true
        fail_below_min: false
        hide_complexity: false

    - name: Add Sticky Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
